version: '3.9'
services:

  api01: &api
    image: crinha-fs:latest
    volumes:
      - ./data:/tmp/data
    hostname: api01  
    command: ./rinha
    environment:
      PORT: 8080
    expose:
      - 8080
    network_mode: "host"    
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '6MB'

  api02:
    <<: *api
    hostname: api02
    environment:
      PORT: 8081
    expose:
      - 8081   
         
  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02  
    # ports:
    #   - "9999:9999"
    network_mode: "host"    
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '16MB'
